name: dartsheet
version: 0.9.0
description: A mobile-friendly web app with routing, responsive CSS, and (optional) Sass support.
dependencies:
  dart_flex: 0.9.0
  observe: any
transformers:
- dart_flex/src/transformers/event_transformer
- $dart2js:
    checked: false
    minify: true
    commandLineOptions:
    - --trust-primitives
