name: dartsheet
version: 0.9.1
description: Dart spreadsheet with RxJs formulas
dependencies:
  dart_flex: 0.9.1
  observe: any
transformers:
- dart_flex/src/transformers/event_transformer
- $dart2js:
    checked: false
    minify: true
    commandLineOptions:
    - --trust-primitives
